# Generated by Django 5.1.5 on 2025-01-28 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='eng_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch_name', models.CharField(max_length=100)),
                ('eng_book_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='hin_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch_name', models.CharField(max_length=100)),
                ('hin_book_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ncert_sol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch_name', models.CharField(max_length=100)),
                ('ncert_sol_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch_name', models.CharField(max_length=100)),
                ('notes_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='work_sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch_name', models.CharField(max_length=100)),
                ('work_sheet_file', models.FileField(upload_to='')),
            ],
        ),
    ]
