# Generated by Django 5.1.5 on 2025-01-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_name',
            name='notes',
            field=models.ManyToManyField(related_name='class_name', to='home.notes'),
        ),
    ]
