# Generated by Django 5.1.5 on 2025-01-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_class_name_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_name',
            name='eng_book',
            field=models.ManyToManyField(related_name='class_name', to='home.eng_book'),
        ),
    ]
