# Generated by Django 5.1.5 on 2025-01-29 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_class_name_eng_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ChapterResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes_file', models.FileField(blank=True, null=True, upload_to='resources/notes/')),
                ('english_book_file', models.FileField(blank=True, null=True, upload_to='resources/english_books/')),
                ('hindi_book_file', models.FileField(blank=True, null=True, upload_to='resources/hindi_books/')),
                ('question_file', models.FileField(blank=True, null=True, upload_to='resources/questions/')),
                ('quiz_file', models.FileField(blank=True, null=True, upload_to='resources/quizzes/')),
                ('chapter_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='home.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('class_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='home.class')),
            ],
        ),
        migrations.RemoveField(
            model_name='class_name',
            name='eng_book',
        ),
        migrations.RemoveField(
            model_name='class_name',
            name='notes',
        ),
        migrations.DeleteModel(
            name='hin_book',
        ),
        migrations.DeleteModel(
            name='ncert_sol',
        ),
        migrations.DeleteModel(
            name='work_sheet',
        ),
        migrations.AddField(
            model_name='chapter',
            name='subject_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='home.subject'),
        ),
        migrations.DeleteModel(
            name='eng_book',
        ),
        migrations.DeleteModel(
            name='Class_name',
        ),
        migrations.DeleteModel(
            name='notes',
        ),
    ]
