# Generated by Django 5.1.5 on 2025-01-29 08:46

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_chapter_chapterresource_class_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapterresource',
            name='english_book_file',
            field=models.FileField(blank=True, null=True, upload_to=home.models.resource_upload_path),
        ),
        migrations.AlterField(
            model_name='chapterresource',
            name='hindi_book_file',
            field=models.FileField(blank=True, null=True, upload_to=home.models.resource_upload_path),
        ),
        migrations.AlterField(
            model_name='chapterresource',
            name='notes_file',
            field=models.FileField(blank=True, null=True, upload_to=home.models.resource_upload_path),
        ),
        migrations.AlterField(
            model_name='chapterresource',
            name='question_file',
            field=models.FileField(blank=True, null=True, upload_to=home.models.resource_upload_path),
        ),
        migrations.AlterField(
            model_name='chapterresource',
            name='quiz_file',
            field=models.FileField(blank=True, null=True, upload_to=home.models.resource_upload_path),
        ),
    ]
