# Generated by Django 5.1.5 on 2025-01-31 10:37

import django.db.models.deletion
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_chapterresource_english_book_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_title', models.CharField(max_length=200)),
                ('quiz_file', models.FileField(blank=True, null=True, upload_to=home.models.resource_upload_path)),
                ('chapter_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='home.chapter')),
            ],
        ),
    ]
