# Generated by Django 5.1.5 on 2025-01-31 11:04

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_quiz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='chapter_fk',
            new_name='chapter',
        ),
        migrations.RemoveField(
            model_name='chapterresource',
            name='quiz_file',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='quiz_title',
        ),
        migrations.AddField(
            model_name='quiz',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_file',
            field=models.FileField(upload_to=home.models.resource_upload_path),
        ),
    ]
