# Generated by Django 5.1.5 on 2025-01-31 15:55

import django.db.models.deletion
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_chapter_fk_quiz_chapter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapterresource',
            old_name='question_file',
            new_name='mind_map',
        ),
        migrations.AddField(
            model_name='chapterresource',
            name='ncert_sol_file',
            field=models.FileField(blank=True, null=True, upload_to=home.models.resource_upload_path),
        ),
        migrations.CreateModel(
            name='Questionsheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Questionsheet_file', models.FileField(upload_to=home.models.resource_upload_path)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_sheet', to='home.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Worksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Worksheet_file', models.FileField(upload_to=home.models.resource_upload_path)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_sheet', to='home.chapter')),
            ],
        ),
    ]
