# Generated by Django 5.1.5 on 2025-02-01 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_question_file_chapterresource_mind_map_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapterresource',
            old_name='chapter_fk',
            new_name='chapter',
        ),
        migrations.RenameField(
            model_name='questionsheet',
            old_name='Questionsheet_file',
            new_name='question_sheet_file',
        ),
        migrations.RenameField(
            model_name='worksheet',
            old_name='Worksheet_file',
            new_name='worksheet_file',
        ),
        migrations.AlterField(
            model_name='questionsheet',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_sheets', to='home.chapter'),
        ),
        migrations.AlterField(
            model_name='worksheet',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worksheets', to='home.chapter'),
        ),
    ]
