# Generated by Django 5.1.5 on 2025-02-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_chapter_fk_chapterresource_chapter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
