# Generated by Django 5.1.5 on 2025-02-02 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_chapter_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='slug',
        ),
    ]
